### ISSUE TITLE
Radiation storms irradiate the Cargo Bay.

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/Baystation12#163] opened 2020-01-21 05:13 UTC
#### Description of issue

Gotten radsick in cargo a couple times now during a radstorm

#### Difference between expected and actual behavior

we're told it's safe.  It's not.  It never was.

#### Steps to reproduce

Upper cargo bay.  Radstorm.  Hang out

#### Specific information for locating

Upper cargo bay.  Lower cargo bay.  I went everywhere.

#### Client version, Server revision & Game ID

Found 1/20/20 most recently

#### Issue bingo

- [x ] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [x ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by MistakeNot4892** [comment] 2020-01-21 08:15
Did some local testing and couldn't reproduce this in the Cargo areas. However:
- If you leave the cargo area/shielded areas after the radstorm, the turfs around you will still be irradiated and will in turn irradiate you.
- The elevator was not shielded, which I've resolved in the PR above.

**Closed** 2020-01-21 08:45 UTC
